//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jan_Fabry_BakalarskaPraca
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reklamacia
    {
        public int ID_Reklamacia { get; set; }
        public System.DateTime Datum_Podania { get; set; }
        public string Stav { get; set; }
        public string Predmet { get; set; }
        public string Uzivatel_Username { get; set; }
    }
}
